name: spring boot deploy

on:
  push:
    branches: [ backend-dev ]

jobs:
  build:
    name: Spring Boot Builder
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Make Directory deploy
        run: mkdir -p deploy

      - name: Move deploy script
        run: cp scripts/*.sh ./deploy/

      - name: Copy Jar
        run: cp build/libs/*.jar app.jar

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          tags: latest