name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:
    name : Spring Boot Builder
    runs-on: CentOS Linux release 7.9.2009

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
